name: Packer PR Checks

on:
  pull_request:
    paths:
      - 'packer/aws-Debian.pkr.hcl' 

jobs:
  packer_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run packer fmt
        run: packer fmt packer/aws-Debian.pkr.hcl

      - name: Check for changes
        id: git-diff
        run: |
          git diff --exit-code || {
            echo "Packer template has been modified during 'packer fmt'. Please make sure your Packer template is properly formatted.";
            exit 1;
          }

      - name: Run packer validate
        run: packer validate packer/aws-Debian.pkr.hcl 

      - name: Check validation status
        id: validate-status
        run: |
          if [ $? -eq 0 ]; then
            echo "Packer template validation succeeded.";
          else
            echo "Packer template validation failed. Please fix any issues before merging.";
            exit 1;
          }

      - name: Final checks
        if: ${{ steps.validate-status.outcome == 'success' }}
        run: echo "All checks passed. Ready to merge."
