name: Build AMI with Packer

on:
  pull_request:
    types:
      - closed

jobs:
  create-zip:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Zip Archive
        run: |
          zip -r Yuvaraj_dalavai_002789615_03.zip .
        working-directory: ${{ github.workspace }}

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          aws configure set default.output json


      - name: Build AMI
        run: |
          packer init ./packer/aws-Debian.pkr.hcl
          packer fmt ./packer/aws-Debian.pkr.hcl
          packer validate ./packer/aws-Debian.pkr.hcl
          packer build ./packer/aws-Debian.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
